---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-flux-config
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/LinuxNerdBTW/flux-config.git
