---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: git-cluster-config
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters/nkp/apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-flux-config
